easy_admin:
    site_name: Conference Guestbook

    design:
        menu:
            - { route: 'homepage', label: 'back_website.label', icon: 'home'}
            - { entity: 'Conference', label: 'conference.label', icon: 'map-marker'}
            - { entity: 'Comment', label: 'comment.label', icon: 'comments'}
    entities:
        # List the entity class name you want to manage
        Conference:
            class: App\Entity\Conference
        Comment:
            class: App\Entity\Comment
            list:
                fields:
                    - author
                    - { property: 'email', type: 'email' }
                    - { property: 'photoFilename', type: 'image', 'base_path': "/uploads/photos", label: 'Photo' }
                    - state
                    - { property: 'createdAt', type: 'datetime' }
                sort: ['createdAt', 'ASC']
                filters: ['conference']
            edit:
                fields:
                    - { property: 'conference' }
                    - { property: 'createdAt', type: 'datetime', type_options: { attr: { readonly: true}}}
                    - 'author'
                    - { property: 'state' }
                    - { property: 'email', type: 'email' }
                    - text
