framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            async:
                dsn: '%env(RABBITMQ_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        failure_transport: failed

        routing:
            App\Message\CommentMessage: async
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
